# Generated by Django 5.2.1 on 2025-06-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='work_examples/', verbose_name='Изображение 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='work_examples/', verbose_name='Изображение 2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='work_examples/', verbose_name='Изображение 3')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='work_examples/', verbose_name='Изображение 4')),
            ],
            options={
                'verbose_name': 'Приемры работ',
                'verbose_name_plural': 'Приемры работ',
            },
        ),
    ]
