# Generated by Django 5.2.1 on 2025-05-27 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Фаска')),
            ],
        ),
        migrations.CreateModel(
            name='ConnectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип соединения')),
            ],
        ),
        migrations.CreateModel(
            name='Construction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Конструкция')),
            ],
        ),
        migrations.CreateModel(
            name='Gloss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Блеск')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Класс')),
            ],
        ),
        migrations.CreateModel(
            name='LaminatePattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип рисунка')),
            ],
        ),
        migrations.CreateModel(
            name='SkirtingBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('type', models.CharField(choices=[('mdf', 'МДФ'), ('aluminum', 'Алюминиевый'), ('duropolymer', 'Дюрополимер'), ('laminated', 'Ламинированный'), ('veneered', 'Шпонированный')], max_length=20, verbose_name='Тип')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('thickness', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Толщина (мм)')),
                ('height', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Высота (мм)')),
                ('moisture_resistance', models.CharField(choices=[('moisture', 'Влагостойкий'), ('waterproof', 'Водостойкий')], max_length=20, verbose_name='Влагостойкость')),
                ('tone', models.CharField(choices=[('light', 'Светлый'), ('dark', 'Темный')], max_length=10, verbose_name='Оттенок')),
                ('image', models.ImageField(upload_to='skirtingBoard/')),
            ],
        ),
        migrations.CreateModel(
            name='Substrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Подложка')),
            ],
        ),
        migrations.CreateModel(
            name='Texture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Поверхность на ощупь')),
            ],
        ),
        migrations.CreateModel(
            name='Thickness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Толщина')),
            ],
        ),
        migrations.CreateModel(
            name='Tone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Оттенок')),
            ],
        ),
        migrations.CreateModel(
            name='Underlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thickness', models.PositiveIntegerField(choices=[(2, '2 мм'), (3, '3 мм'), (5, '5 мм')], verbose_name='Толщина (мм)')),
                ('has_vapor_barrier', models.BooleanField(default=False, verbose_name='С пароизоляцией')),
                ('floor_type', models.CharField(choices=[('water', 'Водяной пол'), ('electric', 'Электрический пол')], max_length=20, verbose_name='Тип пола')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('image', models.ImageField(upload_to='underlay/')),
            ],
        ),
        migrations.CreateModel(
            name='WaterResistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Влагостойкость')),
            ],
        ),
        migrations.CreateModel(
            name='Width',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ширина')),
            ],
        ),
        migrations.CreateModel(
            name='WoodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Порода дерева')),
            ],
        ),
        migrations.CreateModel(
            name='Laminate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name='Скидка')),
                ('image', models.ImageField(upload_to='laminates/')),
                ('is_promo', models.BooleanField(default=False, verbose_name='Акция')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tile.category')),
                ('chamfer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laminate.chamfer')),
                ('connection_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laminate.connectiontype')),
                ('construction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laminate.construction')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tile.country')),
                ('gloss', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laminate.gloss')),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laminate.grade')),
                ('laminate_pattern', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laminate.laminatepattern')),
                ('substrate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laminate.substrate')),
                ('texture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laminate.texture')),
                ('thickness', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laminate.thickness')),
                ('tone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laminate.tone')),
                ('water_resistance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laminate.waterresistance')),
                ('width', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laminate.width')),
                ('wood_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laminate.woodtype')),
            ],
        ),
    ]
