# Generated by Django 5.2.1 on 2025-05-29 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laminate', '0001_initial'),
        ('tile', '0002_alter_category_options_alter_collection_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chamfer',
            options={'verbose_name': 'Фаска ламината', 'verbose_name_plural': 'Фаска ламината'},
        ),
        migrations.AlterModelOptions(
            name='connectiontype',
            options={'verbose_name': 'Тип соединения ламината', 'verbose_name_plural': 'Тип соединения ламината'},
        ),
        migrations.AlterModelOptions(
            name='construction',
            options={'verbose_name': 'Конструкция ламината', 'verbose_name_plural': 'Конструкция ламината'},
        ),
        migrations.AlterModelOptions(
            name='gloss',
            options={'verbose_name': 'Блеск ламината', 'verbose_name_plural': 'Блеск ламината'},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name': 'Класс ламината', 'verbose_name_plural': 'Класс ламината'},
        ),
        migrations.AlterModelOptions(
            name='laminate',
            options={'verbose_name': 'Ламинат', 'verbose_name_plural': 'Ламинат'},
        ),
        migrations.AlterModelOptions(
            name='laminatepattern',
            options={'verbose_name': 'Тип рисунка ламината', 'verbose_name_plural': 'Тип рисунка ламината'},
        ),
        migrations.AlterModelOptions(
            name='skirtingboard',
            options={'verbose_name': 'Плинтус', 'verbose_name_plural': 'Плинтус'},
        ),
        migrations.AlterModelOptions(
            name='substrate',
            options={'verbose_name': 'Подложка для ламината', 'verbose_name_plural': 'Подложка для ламината'},
        ),
        migrations.AlterModelOptions(
            name='texture',
            options={'verbose_name': 'Поверхность на ощупь ламината', 'verbose_name_plural': 'Поверхность на ощупь ламината'},
        ),
        migrations.AlterModelOptions(
            name='thickness',
            options={'verbose_name': 'Толщина ламината', 'verbose_name_plural': 'Толщина ламината'},
        ),
        migrations.AlterModelOptions(
            name='tone',
            options={'verbose_name': 'Оттенок ламината', 'verbose_name_plural': 'Оттенок ламината'},
        ),
        migrations.AlterModelOptions(
            name='underlay',
            options={'verbose_name': 'Подложка', 'verbose_name_plural': 'Подложка'},
        ),
        migrations.AlterModelOptions(
            name='waterresistance',
            options={'verbose_name': 'Влагостойкость ламината', 'verbose_name_plural': 'Влагостойкость ламината'},
        ),
        migrations.AlterModelOptions(
            name='width',
            options={'verbose_name': 'Ширина ламината', 'verbose_name_plural': 'Ширина ламината'},
        ),
        migrations.AlterModelOptions(
            name='woodtype',
            options={'verbose_name': 'Порода дерева ламината', 'verbose_name_plural': 'Порода дерева ламината'},
        ),
        migrations.AlterField(
            model_name='laminate',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tile.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='laminate',
            name='chamfer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laminate.chamfer', verbose_name='Фаска ламината'),
        ),
        migrations.AlterField(
            model_name='laminate',
            name='connection_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laminate.connectiontype', verbose_name='Тип соединения'),
        ),
        migrations.AlterField(
            model_name='laminate',
            name='construction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laminate.construction', verbose_name='Конструкция'),
        ),
        migrations.AlterField(
            model_name='laminate',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tile.country', verbose_name='Страна производитель'),
        ),
        migrations.AlterField(
            model_name='laminate',
            name='gloss',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laminate.gloss', verbose_name='Блеск'),
        ),
        migrations.AlterField(
            model_name='laminate',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laminate.grade', verbose_name='Класс ламината'),
        ),
        migrations.AlterField(
            model_name='laminate',
            name='image',
            field=models.ImageField(upload_to='laminates/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='laminate',
            name='laminate_pattern',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laminate.laminatepattern', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='laminate',
            name='substrate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laminate.substrate', verbose_name='Подложка'),
        ),
        migrations.AlterField(
            model_name='laminate',
            name='texture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laminate.texture', verbose_name='Поверхность на ощупь'),
        ),
        migrations.AlterField(
            model_name='laminate',
            name='thickness',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laminate.thickness', verbose_name='Толщина'),
        ),
        migrations.AlterField(
            model_name='laminate',
            name='tone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laminate.tone', verbose_name='Тип рисунка'),
        ),
        migrations.AlterField(
            model_name='laminate',
            name='water_resistance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laminate.waterresistance', verbose_name='Влагостойкость'),
        ),
        migrations.AlterField(
            model_name='laminate',
            name='width',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laminate.width', verbose_name='Ширина'),
        ),
        migrations.AlterField(
            model_name='laminate',
            name='wood_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laminate.woodtype', verbose_name='Порода дерева'),
        ),
    ]
