# Generated by Django 5.2.1 on 2025-05-29 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laminate', '0002_alter_chamfer_options_alter_connectiontype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laminate',
            name='substrate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laminate.underlay', verbose_name='Подложка'),
        ),
        migrations.AddField(
            model_name='underlay',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='laminate',
            name='image',
            field=models.ImageField(upload_to='laminates/', verbose_name='Изображение'),
        ),
        migrations.DeleteModel(
            name='Substrate',
        ),
    ]
