# Generated by Django 5.2.1 on 2025-05-29 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laminate', '0003_alter_laminate_substrate_underlay_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Substrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Подложка')),
            ],
            options={
                'verbose_name': 'Подложка для ламината',
                'verbose_name_plural': 'Подложка для ламината',
            },
        ),
        migrations.AlterField(
            model_name='underlay',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='laminate',
            name='substrate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laminate.substrate', verbose_name='Подложка'),
        ),
    ]
