# Generated by Django 5.2.1 on 2025-05-29 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laminate', '0004_substrate_alter_underlay_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laminate',
            name='substrate',
        ),
        migrations.AddField(
            model_name='laminate',
            name='is_substrate',
            field=models.BooleanField(default=False, verbose_name='Наличие подолжки'),
        ),
        migrations.DeleteModel(
            name='Substrate',
        ),
    ]
