# Generated by Django 5.2.1 on 2025-05-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laminate', '0005_remove_laminate_substrate_laminate_is_substrate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laminate',
            name='board_dimensions',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Размеры доски в мм'),
        ),
        migrations.AddField(
            model_name='laminate',
            name='boards_in_packaging',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество досок в упаковке'),
        ),
        migrations.AddField(
            model_name='laminate',
            name='package_volume',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Объем упаковки'),
        ),
        migrations.AddField(
            model_name='laminate',
            name='package_weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='Вес упаковки'),
        ),
        migrations.AddField(
            model_name='laminate',
            name='quadrature',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Количество квадратов в упаковке'),
        ),
    ]
