# Generated by Django 5.2.1 on 2025-05-29 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laminate', '0006_laminate_board_dimensions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laminate',
            name='image',
        ),
        migrations.RemoveField(
            model_name='skirtingboard',
            name='image',
        ),
        migrations.RemoveField(
            model_name='underlay',
            name='image',
        ),
        migrations.AddField(
            model_name='laminate',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='laminate',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='laminates/', verbose_name='Изображение 1'),
        ),
        migrations.AddField(
            model_name='laminate',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='laminates/', verbose_name='Изображение 2'),
        ),
        migrations.AddField(
            model_name='laminate',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='laminates/', verbose_name='Изображение 3'),
        ),
        migrations.AddField(
            model_name='laminate',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='laminates/', verbose_name='Изображение 4'),
        ),
        migrations.AddField(
            model_name='laminate',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='laminates/', verbose_name='Изображение 5'),
        ),
        migrations.AddField(
            model_name='skirtingboard',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='skirtingBoard/', verbose_name='Изображение 1'),
        ),
        migrations.AddField(
            model_name='skirtingboard',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='skirtingBoard/', verbose_name='Изображение 2'),
        ),
        migrations.AddField(
            model_name='skirtingboard',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='skirtingBoard/', verbose_name='Изображение 3'),
        ),
        migrations.AddField(
            model_name='skirtingboard',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='skirtingBoard/', verbose_name='Изображение 4'),
        ),
        migrations.AddField(
            model_name='skirtingboard',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='skirtingBoard/', verbose_name='Изображение 5'),
        ),
        migrations.AddField(
            model_name='underlay',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='underlay/', verbose_name='Изображение 1'),
        ),
        migrations.AddField(
            model_name='underlay',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='underlay/', verbose_name='Изображение 2'),
        ),
        migrations.AddField(
            model_name='underlay',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='underlay/', verbose_name='Изображение 3'),
        ),
        migrations.AddField(
            model_name='underlay',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='underlay/', verbose_name='Изображение 4'),
        ),
        migrations.AddField(
            model_name='underlay',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='underlay/', verbose_name='Изображение 5'),
        ),
        migrations.AlterField(
            model_name='laminate',
            name='laminate_pattern',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laminate.laminatepattern', verbose_name='Рисунок ламината'),
        ),
        migrations.AlterField(
            model_name='laminate',
            name='tone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laminate.tone', verbose_name='Оттенок'),
        ),
    ]
