# Generated by Django 5.2.1 on 2025-05-30 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laminate', '0007_remove_laminate_image_remove_skirtingboard_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laminate',
            name='chamfer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laminate.chamfer', verbose_name='Фаска'),
        ),
        migrations.AlterField(
            model_name='laminate',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laminate.grade', verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='laminate',
            name='laminate_pattern',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='laminate.laminatepattern', verbose_name='Рисунок'),
        ),
    ]
