# Generated by Django 5.2.1 on 2025-06-03 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laminate', '0008_alter_laminate_chamfer_alter_laminate_grade_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chamfer',
            options={'verbose_name': 'Фаска', 'verbose_name_plural': 'Фаска ламината'},
        ),
        migrations.AlterModelOptions(
            name='connectiontype',
            options={'verbose_name': 'Тип соединения', 'verbose_name_plural': 'Тип соединения ламината'},
        ),
        migrations.AlterModelOptions(
            name='construction',
            options={'verbose_name': 'Конструкция', 'verbose_name_plural': 'Конструкция ламината'},
        ),
        migrations.AlterModelOptions(
            name='gloss',
            options={'verbose_name': 'Блеск', 'verbose_name_plural': 'Блеск ламината'},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name': 'Класс', 'verbose_name_plural': 'Класс ламината'},
        ),
        migrations.AlterModelOptions(
            name='laminatepattern',
            options={'verbose_name': 'Тип рисунка', 'verbose_name_plural': 'Тип рисунка ламината'},
        ),
        migrations.AlterModelOptions(
            name='texture',
            options={'verbose_name': 'Поверхность на ощупь', 'verbose_name_plural': 'Поверхность на ощупь ламината'},
        ),
        migrations.AlterModelOptions(
            name='thickness',
            options={'verbose_name': 'Толщина', 'verbose_name_plural': 'Толщина ламината'},
        ),
        migrations.AlterModelOptions(
            name='tone',
            options={'verbose_name': 'Оттенок', 'verbose_name_plural': 'Оттенок ламината'},
        ),
        migrations.AlterModelOptions(
            name='waterresistance',
            options={'verbose_name': 'Влагостойкость', 'verbose_name_plural': 'Влагостойкость ламината'},
        ),
        migrations.AlterModelOptions(
            name='width',
            options={'verbose_name': 'Ширина', 'verbose_name_plural': 'Ширина ламината'},
        ),
        migrations.AlterModelOptions(
            name='woodtype',
            options={'verbose_name': 'Порода дерева', 'verbose_name_plural': 'Порода дерева ламината'},
        ),
    ]
