# Generated by Django 5.2.1 on 2025-07-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laminate', '0009_alter_chamfer_options_alter_connectiontype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laminate',
            name='type',
            field=models.CharField(default='laminate'),
        ),
    ]
