# Generated by Django 5.2.1 on 2025-07-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laminate', '0010_laminate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='underlay',
            name='type',
            field=models.CharField(default='underlay'),
        ),
    ]
