# Generated by Django 5.2.1 on 2025-07-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laminate', '0011_underlay_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skirtingboard',
            name='type',
            field=models.CharField(default='skirtingBoard'),
        ),
    ]
