# Generated by Django 5.2.1 on 2025-07-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laminate', '0012_alter_skirtingboard_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skirtingboard',
            name='type',
            field=models.CharField(default='skirtingboard'),
        ),
    ]
