# Generated by Django 5.2.1 on 2025-07-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laminate', '0014_skirtingboard_typeproduct_alter_skirtingboard_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skirtingboard',
            name='typeproduct',
        ),
        migrations.AddField(
            model_name='skirtingboard',
            name='typematerial',
            field=models.CharField(choices=[('mdf', 'МДФ'), ('aluminum', 'Алюминиевый'), ('duropolymer', 'Дюрополимер'), ('laminated', 'Ламинированный'), ('veneered', 'Шпонированный')], default='mdf', max_length=20, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='skirtingboard',
            name='type',
            field=models.CharField(default='skirtingboard'),
        ),
    ]
