# Generated by Django 5.2.1 on 2025-07-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laminate', '0015_remove_skirtingboard_typeproduct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skirtingboard',
            name='typematerial',
            field=models.CharField(choices=[('mdf', 'МДФ'), ('aluminum', 'Алюминиевый'), ('duropolymer', 'Дюрополимер'), ('laminated', 'Ламинированный'), ('veneered', 'Шпонированный')], max_length=20, verbose_name='Тип'),
        ),
    ]
