# Generated by Django 4.2.23 on 2025-07-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laminate', '0016_alter_skirtingboard_typematerial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laminate',
            name='type',
            field=models.CharField(default='laminate', max_length=255),
        ),
        migrations.AlterField(
            model_name='skirtingboard',
            name='type',
            field=models.CharField(default='skirtingboard', max_length=255),
        ),
        migrations.AlterField(
            model_name='underlay',
            name='type',
            field=models.CharField(default='underlay', max_length=255),
        ),
    ]
