# Generated by Django 5.2.1 on 2025-05-29 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Название категории', 'verbose_name_plural': 'Категория'},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': 'Коллекция', 'verbose_name_plural': 'Коллекция'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Цвет', 'verbose_name_plural': 'Цвет'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Страна', 'verbose_name_plural': 'Страна'},
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name': 'Особенность', 'verbose_name_plural': 'Особенность'},
        ),
        migrations.AlterModelOptions(
            name='form',
            options={'verbose_name': 'Форма', 'verbose_name_plural': 'Форма'},
        ),
        migrations.AlterModelOptions(
            name='grout',
            options={'verbose_name': 'Замазка', 'verbose_name_plural': 'Замазка'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Материал', 'verbose_name_plural': 'Материал'},
        ),
        migrations.AlterModelOptions(
            name='pattern',
            options={'verbose_name': 'Рисунок', 'verbose_name_plural': 'Рисунок'},
        ),
        migrations.AlterModelOptions(
            name='purpose',
            options={'verbose_name': 'Назначение', 'verbose_name_plural': 'Назначение'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Помещение', 'verbose_name_plural': 'Помещение'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'Размер', 'verbose_name_plural': 'Размер'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'Слайдер', 'verbose_name_plural': 'Слайдер'},
        ),
        migrations.AlterModelOptions(
            name='style',
            options={'verbose_name': 'Стиль', 'verbose_name_plural': 'Стиль'},
        ),
        migrations.AlterModelOptions(
            name='surface',
            options={'verbose_name': 'Поверхность', 'verbose_name_plural': 'Поверхность'},
        ),
        migrations.AlterModelOptions(
            name='tile',
            options={'verbose_name': 'Плитка', 'verbose_name_plural': 'Плитка'},
        ),
        migrations.AddField(
            model_name='tile',
            name='is_large_format',
            field=models.BooleanField(default=False, verbose_name='Крупный формат'),
        ),
        migrations.AlterField(
            model_name='tile',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tile.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='tile',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tile.collection', verbose_name='Коллекция'),
        ),
        migrations.AlterField(
            model_name='tile',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tile.color', verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='tile',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tile.country', verbose_name='Страна производитель'),
        ),
        migrations.AlterField(
            model_name='tile',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tile',
            name='features',
            field=models.ManyToManyField(to='tile.feature', verbose_name='Особенности'),
        ),
        migrations.AlterField(
            model_name='tile',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tile.form', verbose_name='Форма'),
        ),
        migrations.AlterField(
            model_name='tile',
            name='image',
            field=models.ImageField(upload_to='tiles/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='tile',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tile.material', verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='tile',
            name='pattern',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tile.pattern', verbose_name='Рисунок'),
        ),
        migrations.AlterField(
            model_name='tile',
            name='purpose',
            field=models.ManyToManyField(to='tile.purpose', verbose_name='Предназначение'),
        ),
        migrations.AlterField(
            model_name='tile',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tile.room', verbose_name='Помещение'),
        ),
        migrations.AlterField(
            model_name='tile',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tile.size', verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='tile',
            name='style',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tile.style', verbose_name='Стиль'),
        ),
        migrations.AlterField(
            model_name='tile',
            name='surface',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tile.surface', verbose_name='Поверхность на ощупь'),
        ),
    ]
