# Generated by Django 5.2.1 on 2025-05-29 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tile', '0002_alter_category_options_alter_collection_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grout',
            name='image',
        ),
        migrations.RemoveField(
            model_name='tile',
            name='image',
        ),
        migrations.AddField(
            model_name='grout',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='grouts/', verbose_name='Фотография 1'),
        ),
        migrations.AddField(
            model_name='grout',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='grouts/', verbose_name='Фотография 2'),
        ),
        migrations.AddField(
            model_name='grout',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='grouts/', verbose_name='Фотография 3'),
        ),
        migrations.AddField(
            model_name='grout',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='grouts/', verbose_name='Фотография 4'),
        ),
        migrations.AddField(
            model_name='grout',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='grouts/', verbose_name='Фотография 5'),
        ),
        migrations.AddField(
            model_name='tile',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='tiles/', verbose_name='Изображение 1'),
        ),
        migrations.AddField(
            model_name='tile',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='tiles/', verbose_name='Изображение 2'),
        ),
        migrations.AddField(
            model_name='tile',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='tiles/', verbose_name='Изображение 3'),
        ),
        migrations.AddField(
            model_name='tile',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='tiles/', verbose_name='Изображение 4'),
        ),
        migrations.AddField(
            model_name='tile',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='tiles/', verbose_name='Изображение 5'),
        ),
    ]
