# Generated by Django 5.2.1 on 2025-06-03 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tile', '0003_remove_grout_image_remove_tile_image_grout_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='colors',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Цвета'),
        ),
        migrations.AddField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='collection',
            name='formats',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Форматы'),
        ),
        migrations.AddField(
            model_name='collection',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='collections/', verbose_name='Изображение1'),
        ),
        migrations.AddField(
            model_name='collection',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='collections/', verbose_name='Изображение2'),
        ),
        migrations.AddField(
            model_name='collection',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='collections/', verbose_name='Изображение3'),
        ),
        migrations.AddField(
            model_name='collection',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='collections/', verbose_name='Изображение4'),
        ),
        migrations.AddField(
            model_name='collection',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='collections/', verbose_name='Изображение5'),
        ),
        migrations.AddField(
            model_name='collection',
            name='main_size',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Основной размер'),
        ),
        migrations.AddField(
            model_name='collection',
            name='pattern',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Рисунок'),
        ),
        migrations.AddField(
            model_name='collection',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='collection',
            name='scope_of_application',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Область применения'),
        ),
        migrations.AddField(
            model_name='tile',
            name='tile_type',
            field=models.CharField(choices=[('base', 'Базовая плитка'), ('border', 'Бордюр'), ('inlay', 'Вставка'), ('panel', 'Панно'), ('corner', 'Угловой элемент'), ('step', 'Ступень'), ('riser', 'Подступень'), ('plinth', 'Плинтус')], default='base', max_length=10),
        ),
        migrations.AlterField(
            model_name='tile',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tiles', to='tile.collection', verbose_name='Коллекция'),
        ),
    ]
