# Generated by Django 5.2.1 on 2025-06-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tile', '0004_collection_colors_collection_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='popularity_score',
            field=models.IntegerField(default=1, verbose_name='Популярность от 1 до 10'),
        ),
    ]
