# Generated by Django 5.2.1 on 2025-06-04 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tile', '0005_tile_popularity_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='popularity_score',
            field=models.IntegerField(default=1, verbose_name='Популярность от 1 до 10'),
        ),
    ]
