# Generated by Django 5.2.1 on 2025-06-04 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tile', '0006_collection_popularity_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='popularity_score',
            field=models.PositiveBigIntegerField(default=1, verbose_name='Популярность от 1 до 10'),
        ),
    ]
