# Generated by Django 5.2.1 on 2025-06-04 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tile', '0007_alter_collection_popularity_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='country',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='tile.country', verbose_name='Страна'),
        ),
    ]
