# Generated by Django 5.2.1 on 2025-06-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tile', '0008_collection_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='number_of_elements',
            field=models.IntegerField(default=3, verbose_name='Количество элементов'),
        ),
    ]
