# Generated by Django 5.2.1 on 2025-06-06 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tile', '0009_collection_number_of_elements'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='compound',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Состав коллекции'),
        ),
        migrations.AddField(
            model_name='collection',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='collections/logo/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название коллекции'),
        ),
    ]
