# Generated by Django 5.2.1 on 2025-06-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tile', '0010_collection_compound_collection_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='style',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Стиль'),
        ),
    ]
