# Generated by Django 5.2.1 on 2025-07-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tile', '0013_grout_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='type',
            field=models.CharField(default='tile'),
        ),
        migrations.AlterField(
            model_name='tile',
            name='tile_type',
            field=models.CharField(choices=[('base', 'Базовая плитка'), ('border', 'Бордюр'), ('inlay', 'Вставка'), ('panel', 'Панно'), ('corner', 'Угловой элемент'), ('step', 'Ступень'), ('riser', 'Подступень'), ('plinth', 'Плинтус'), ('floor', 'напольная')], default='base', max_length=10, verbose_name='тип плитки'),
        ),
    ]
