# Generated by Django 5.2.1 on 2025-07-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tile', '0014_tile_type_alter_tile_tile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='grout',
            name='typematerial',
            field=models.CharField(blank=True, choices=[('cement', 'цементный'), ('epoxy', 'эпоксидный'), ('polymeric', 'полимерный'), ('polyurethane', 'полиуритановый'), ('silicone', 'силиконовый')], default='', max_length=20, null=True, verbose_name='Тип замазки'),
        ),
        migrations.AlterField(
            model_name='grout',
            name='type',
            field=models.CharField(default='grout'),
        ),
    ]
