# Generated by Django 4.2.23 on 2025-07-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tile', '0015_grout_typematerial_alter_grout_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grout',
            name='type',
            field=models.CharField(default='grout', max_length=255),
        ),
        migrations.AlterField(
            model_name='tile',
            name='type',
            field=models.CharField(default='tile', max_length=255),
        ),
    ]
