# Generated by Django 5.2.1 on 2025-07-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tile', '0015_grout_typematerial_alter_grout_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='type',
            field=models.CharField(default='collection', max_length=255),
        ),
    ]
