# Generated by Django 4.2.23 on 2025-07-29 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tile', '0016_alter_grout_type_alter_tile_type'),
        ('tile', '0016_collection_type'),
    ]

    operations = [
    ]
