# Generated by Django 5.2.1 on 2025-05-19 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Особенность')),
            ],
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назначение')),
            ],
        ),
        migrations.CreateModel(
            name='Laminate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Скидка')),
                ('image', models.ImageField(upload_to='laminates/', verbose_name='Фотография')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('grade', models.CharField(max_length=50, verbose_name='Класс')),
                ('thickness', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Толщина')),
                ('water_resistant', models.BooleanField(default=False, verbose_name='Влагостойкость')),
                ('chamfer', models.CharField(max_length=100, verbose_name='Фаска')),
                ('pattern', models.CharField(max_length=100, verbose_name='Рисунок')),
                ('surface', models.CharField(max_length=100, verbose_name='Поверхность')),
                ('wood_type', models.CharField(max_length=100, verbose_name='Порода дерева')),
                ('is_promo', models.BooleanField(default=False, verbose_name='Акция')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.category', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Скидка')),
                ('image', models.ImageField(upload_to='tiles/', verbose_name='Фотография')),
                ('material', models.CharField(max_length=100, verbose_name='Материал')),
                ('room', models.CharField(max_length=100, verbose_name='Помещение')),
                ('size', models.CharField(max_length=100, verbose_name='Размер')),
                ('color', models.CharField(max_length=100, verbose_name='Цвет')),
                ('pattern', models.CharField(max_length=100, verbose_name='Рисунок')),
                ('surface', models.CharField(max_length=100, verbose_name='Поверхность')),
                ('shape', models.CharField(max_length=100, verbose_name='Форма')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новинка')),
                ('is_promo', models.BooleanField(default=False, verbose_name='Акция')),
                ('style', models.CharField(max_length=100, verbose_name='Стиль')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('collection', models.CharField(max_length=100, verbose_name='Коллекция')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.category', verbose_name='Категория')),
                ('features', models.ManyToManyField(to='sale.feature', verbose_name='Особенности')),
                ('purpose', models.ManyToManyField(to='sale.purpose', verbose_name='Назначение')),
            ],
        ),
    ]
