# Generated by Django 5.2.1 on 2025-07-03 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advice',
            old_name='descri',
            new_name='description',
        ),
    ]
