# Generated by Django 5.2.1 on 2025-07-15 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advice', '0002_rename_descri_advice_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advice',
            options={'verbose_name': 'Полезные советы', 'verbose_name_plural': 'Полезные советы'},
        ),
    ]
