# Generated by Django 5.2.1 on 2025-06-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='favorite',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='favorite',
            name='image1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='favorite',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favorite',
            name='number_of_elements',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='favorite',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
